
/*
  __        ___.         .__          __
_/  |______ \_ |__  __ __|  | _____ _/  |_  ____
\   __\__  \ | __ \|  |  \  | \__  \\   __\/ __ \
 |  |  / __ \| \_\ \  |  /  |__/ __ \|  | \  ___/
 |__| (____  /___  /____/|____(____  /__|  \___  >
           \/    \/                \/          \/
Table Maker for Modern C++
https://github.com/p-ranav/tabulate

Licensed under the MIT License <http://opensource.org/licenses/MIT>.
SPDX-License-Identifier: MIT
Copyright (c) 2019 Pranav Srinivas Kumar <pranav.srinivas.kumar@gmail.com>.

Permission is hereby  granted, free of charge, to any  person obtaining a copy
of this software and associated  documentation files (the "Software"), to deal
in the Software  without restriction, including without  limitation the rights
to  use, copy,  modify, merge,  publish, distribute,  sublicense, and/or  sell
copies  of  the Software,  and  to  permit persons  to  whom  the Software  is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE  IS PROVIDED "AS  IS", WITHOUT WARRANTY  OF ANY KIND,  EXPRESS OR
IMPLIED,  INCLUDING BUT  NOT  LIMITED TO  THE  WARRANTIES OF  MERCHANTABILITY,
FITNESS FOR  A PARTICULAR PURPOSE AND  NONINFRINGEMENT. IN NO EVENT  SHALL THE
AUTHORS  OR COPYRIGHT  HOLDERS  BE  LIABLE FOR  ANY  CLAIM,  DAMAGES OR  OTHER
LIABILITY, WHETHER IN AN ACTION OF  CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE  OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
#pragma once
#include <algorithm>
#include <cstdint>
#include <string>

#include <clocale>
#include <locale>

#include <cstdlib>
#include <cwchar>
#include <tabulate/termcolor.hpp>
#include <wchar.h>

namespace tabulate {

// Advance past the ANSI escape sequence starting at p, which must point at an
// ESC byte, and return a pointer to the first byte after the sequence. Escape
// sequences occupy no columns on screen, so every width calculation has to be
// able to step over them.
inline const char *skip_ansi_escape_sequence(const char *p) {
  const unsigned char introducer = static_cast<unsigned char>(p[1]);

  // CSI: parameter bytes, then intermediate bytes, then one final byte
  if (introducer == '[') {
    p += 2;
    while (*p != '\0' && static_cast<unsigned char>(*p) >= 0x30 &&
           static_cast<unsigned char>(*p) <= 0x3f)
      ++p;
    while (*p != '\0' && static_cast<unsigned char>(*p) >= 0x20 &&
           static_cast<unsigned char>(*p) <= 0x2f)
      ++p;
    if (*p != '\0')
      ++p;
    return p;
  }

  // OSC, DCS, SOS, PM and APC run until a string terminator; OSC also accepts
  // a BEL as the terminator
  if (introducer == ']' || introducer == 'P' || introducer == 'X' || introducer == '^' ||
      introducer == '_') {
    const bool bel_terminated = introducer == ']';
    p += 2;
    while (*p != '\0') {
      if (bel_terminated && static_cast<unsigned char>(*p) == 0x07)
        return p + 1;
      if (static_cast<unsigned char>(*p) == 0x1b && p[1] == '\\')
        return p + 2;
      ++p;
    }
    return p;
  }

  // Two-character escape sequence
  if (introducer >= 0x40 && introducer <= 0x7e)
    return p + 2;

  return p + 1;
}

#if defined(_WIN32) || defined(_WIN64)
// wcwidth() is a POSIX API and isn't available on Windows, and the width a
// console actually renders a character with doesn't depend on the current
// locale the way *nix's wcwidth() does. mk_wcwidth() is Markus Kuhn's public
// domain implementation (https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c),
// ported to char32_t, which tells us the display width directly from the
// Unicode code point: 0 for combining/zero-width characters, 1 for ordinary
// characters, and 2 for wide (e.g. CJK) characters.
struct unicode_interval {
  char32_t first;
  char32_t last;
};

inline bool in_interval_table(char32_t ucs, const unicode_interval *table, int table_size) {
  int min = 0, max = table_size - 1;
  if (table_size == 0 || ucs < table[0].first || ucs > table[max].last)
    return false;
  while (max >= min) {
    int mid = (min + max) / 2;
    if (ucs > table[mid].last)
      min = mid + 1;
    else if (ucs < table[mid].first)
      max = mid - 1;
    else
      return true;
  }
  return false;
}

inline int mk_wcwidth(char32_t ucs) {
  // Sorted list of non-overlapping intervals of non-spacing characters,
  // generated by "uniset +cat=Me +cat=Mn +cat=Cf -00AD +1160-11FF +200B c"
  static const unicode_interval combining[] = {
      {0x0300, 0x036F},   {0x0483, 0x0486},   {0x0488, 0x0489},   {0x0591, 0x05BD},
      {0x05BF, 0x05BF},   {0x05C1, 0x05C2},   {0x05C4, 0x05C5},   {0x05C7, 0x05C7},
      {0x0600, 0x0603},   {0x0610, 0x0615},   {0x064B, 0x065E},   {0x0670, 0x0670},
      {0x06D6, 0x06E4},   {0x06E7, 0x06E8},   {0x06EA, 0x06ED},   {0x070F, 0x070F},
      {0x0711, 0x0711},   {0x0730, 0x074A},   {0x07A6, 0x07B0},   {0x07EB, 0x07F3},
      {0x0901, 0x0902},   {0x093C, 0x093C},   {0x0941, 0x0948},   {0x094D, 0x094D},
      {0x0951, 0x0954},   {0x0962, 0x0963},   {0x0981, 0x0981},   {0x09BC, 0x09BC},
      {0x09C1, 0x09C4},   {0x09CD, 0x09CD},   {0x09E2, 0x09E3},   {0x0A01, 0x0A02},
      {0x0A3C, 0x0A3C},   {0x0A41, 0x0A42},   {0x0A47, 0x0A48},   {0x0A4B, 0x0A4D},
      {0x0A70, 0x0A71},   {0x0A81, 0x0A82},   {0x0ABC, 0x0ABC},   {0x0AC1, 0x0AC5},
      {0x0AC7, 0x0AC8},   {0x0ACD, 0x0ACD},   {0x0AE2, 0x0AE3},   {0x0B01, 0x0B01},
      {0x0B3C, 0x0B3C},   {0x0B3F, 0x0B3F},   {0x0B41, 0x0B43},   {0x0B4D, 0x0B4D},
      {0x0B56, 0x0B56},   {0x0B82, 0x0B82},   {0x0BC0, 0x0BC0},   {0x0BCD, 0x0BCD},
      {0x0C3E, 0x0C40},   {0x0C46, 0x0C48},   {0x0C4A, 0x0C4D},   {0x0C55, 0x0C56},
      {0x0CBC, 0x0CBC},   {0x0CBF, 0x0CBF},   {0x0CC6, 0x0CC6},   {0x0CCC, 0x0CCD},
      {0x0CE2, 0x0CE3},   {0x0D41, 0x0D43},   {0x0D4D, 0x0D4D},   {0x0DCA, 0x0DCA},
      {0x0DD2, 0x0DD4},   {0x0DD6, 0x0DD6},   {0x0E31, 0x0E31},   {0x0E34, 0x0E3A},
      {0x0E47, 0x0E4E},   {0x0EB1, 0x0EB1},   {0x0EB4, 0x0EB9},   {0x0EBB, 0x0EBC},
      {0x0EC8, 0x0ECD},   {0x0F18, 0x0F19},   {0x0F35, 0x0F35},   {0x0F37, 0x0F37},
      {0x0F39, 0x0F39},   {0x0F71, 0x0F7E},   {0x0F80, 0x0F84},   {0x0F86, 0x0F87},
      {0x0F90, 0x0F97},   {0x0F99, 0x0FBC},   {0x0FC6, 0x0FC6},   {0x102D, 0x1030},
      {0x1032, 0x1032},   {0x1036, 0x1037},   {0x1039, 0x1039},   {0x1058, 0x1059},
      {0x1160, 0x11FF},   {0x135F, 0x135F},   {0x1712, 0x1714},   {0x1732, 0x1734},
      {0x1752, 0x1753},   {0x1772, 0x1773},   {0x17B4, 0x17B5},   {0x17B7, 0x17BD},
      {0x17C6, 0x17C6},   {0x17C9, 0x17D3},   {0x17DD, 0x17DD},   {0x180B, 0x180D},
      {0x18A9, 0x18A9},   {0x1920, 0x1922},   {0x1927, 0x1928},   {0x1932, 0x1932},
      {0x1939, 0x193B},   {0x1A17, 0x1A18},   {0x1B00, 0x1B03},   {0x1B34, 0x1B34},
      {0x1B36, 0x1B3A},   {0x1B3C, 0x1B3C},   {0x1B42, 0x1B42},   {0x1B6B, 0x1B73},
      {0x1DC0, 0x1DCA},   {0x1DFE, 0x1DFF},   {0x200B, 0x200F},   {0x202A, 0x202E},
      {0x2060, 0x2063},   {0x206A, 0x206F},   {0x20D0, 0x20EF},   {0x302A, 0x302F},
      {0x3099, 0x309A},   {0xA806, 0xA806},   {0xA80B, 0xA80B},   {0xA825, 0xA826},
      {0xFB1E, 0xFB1E},   {0xFE00, 0xFE0F},   {0xFE20, 0xFE23},   {0xFEFF, 0xFEFF},
      {0xFFF9, 0xFFFB},   {0x10A01, 0x10A03}, {0x10A05, 0x10A06}, {0x10A0C, 0x10A0F},
      {0x10A38, 0x10A3A}, {0x10A3F, 0x10A3F}, {0x1D167, 0x1D169}, {0x1D173, 0x1D182},
      {0x1D185, 0x1D18B}, {0x1D1AA, 0x1D1AD}, {0x1D242, 0x1D244}, {0xE0001, 0xE0001},
      {0xE0020, 0xE007F}, {0xE0100, 0xE01EF},
  };

  if (ucs == 0)
    return 0;
  // C0/C1 control characters
  if (ucs < 32 || (ucs >= 0x7f && ucs < 0xa0))
    return -1;

  if (in_interval_table(ucs, combining, sizeof(combining) / sizeof(combining[0])))
    return 0;

  return 1 +
         (ucs >= 0x1100 &&
          (ucs <= 0x115f || // Hangul Jamo init. consonants
           ucs == 0x2329 || ucs == 0x232a ||
           (ucs >= 0x2e80 && ucs <= 0xa4cf && ucs != 0x303f) || // CJK ... Yi
           (ucs >= 0xac00 && ucs <= 0xd7a3) ||                  // Hangul Syllables
           (ucs >= 0xf900 && ucs <= 0xfaff) || // CJK Compatibility Ideographs
           (ucs >= 0xfe30 && ucs <= 0xfe6f) ||  // CJK Compatibility Forms
           (ucs >= 0xff00 && ucs <= 0xff60) ||  // Fullwidth Forms
           (ucs >= 0xffe0 && ucs <= 0xffe6) ||
           (ucs >= 0x20000 && ucs <= 0x2fffd) || (ucs >= 0x30000 && ucs <= 0x3fffd)));
}

// Decodes the UTF-8 character starting at p and sets length to the number of
// bytes it occupies. On an invalid or truncated sequence, treats the lead
// byte as a standalone width-1 character and sets length to 1, same as the
// *nix mbrtowc() error handling below.
inline char32_t decode_utf8_codepoint(const char *p, size_t &length) {
  const unsigned char lead = static_cast<unsigned char>(*p);
  size_t continuation_bytes;
  char32_t codepoint;
  if (lead < 0x80) {
    length = 1;
    return lead;
  } else if ((lead & 0xE0) == 0xC0) {
    continuation_bytes = 1;
    codepoint = lead & 0x1F;
  } else if ((lead & 0xF0) == 0xE0) {
    continuation_bytes = 2;
    codepoint = lead & 0x0F;
  } else if ((lead & 0xF8) == 0xF0) {
    continuation_bytes = 3;
    codepoint = lead & 0x07;
  } else {
    length = 1;
    return lead;
  }

  for (size_t i = 1; i <= continuation_bytes; ++i) {
    const unsigned char continuation = static_cast<unsigned char>(p[i]);
    if ((continuation & 0xC0) != 0x80) {
      length = 1;
      return lead;
    }
    codepoint = (codepoint << 6) | (continuation & 0x3F);
  }
  length = continuation_bytes + 1;
  return codepoint;
}

// Display width (in terminal columns) of string, mirroring get_wcswidth()
// below but using mk_wcwidth() instead of the system's locale-dependent
// wcwidth(), since Windows has neither.
inline int get_display_width(const std::string &string, size_t max_characters) {
  if (string.empty())
    return 0;

  const char *p = string.c_str();
  size_t characters = 0;
  int result = 0;

  while (*p != '\0' && characters < max_characters) {
    if (static_cast<unsigned char>(*p) == 0x1b) {
      p = skip_ansi_escape_sequence(p);
      continue;
    }

    size_t length;
    const char32_t codepoint = decode_utf8_codepoint(p, length);
    const int character_width = mk_wcwidth(codepoint);
    if (character_width > 0)
      result += character_width;

    ++characters;
    p += length;
  }

  return result;
}
#endif

#if defined(__unix__) || defined(__unix) || defined(__APPLE__)
inline int get_wcswidth(const std::string &string, const std::string &locale,
                        size_t max_column_width) {
  if (string.size() == 0)
    return 0;

  // The behavior of wcwidth() depends on the LC_CTYPE category of the current
  // locale. Set the current locale based on cell properties before computing
  // width, and put back exactly what was there before.
  const char *previous_locale = std::setlocale(LC_CTYPE, nullptr);
  const std::string saved_locale = previous_locale != nullptr ? previous_locale : "";
  std::setlocale(LC_CTYPE, locale.c_str());

  const char *p = string.c_str();
  std::mbstate_t state = std::mbstate_t();
  size_t characters = 0;
  int result = 0;

  while (*p != '\0' && characters < max_column_width) {
    if (static_cast<unsigned char>(*p) == 0x1b) {
      p = skip_ansi_escape_sequence(p);
      continue;
    }

    wchar_t wide_character;
    size_t length = std::mbrtowc(&wide_character, p, MB_CUR_MAX, &state);

    // Truncated multi-byte character at the end of the string
    if (length == static_cast<size_t>(-2))
      break;

    // Invalid byte, skip it and resynchronize
    if (length == static_cast<size_t>(-1)) {
      state = std::mbstate_t();
      ++p;
      continue;
    }

    if (length == 0)
      length = 1;

    // wcwidth() returns 0 for combining characters and -1 for non-printable
    // ones; neither of those advances the cursor
    const int character_width = wcwidth(wide_character);
    if (character_width > 0)
      result += character_width;

    ++characters;
    p += length;
  }

  if (!saved_locale.empty())
    std::setlocale(LC_CTYPE, saved_locale.c_str());

  return result;
}
#endif

// Number of bytes in text that are not part of an ANSI escape sequence, with
// UTF-8 continuation bytes optionally left out of the count
inline size_t count_bytes_outside_ansi_escapes(const std::string &text,
                                               bool skip_utf8_continuation_bytes) {
  size_t length = 0;
  for (const char *p = text.c_str(); *p != '\0';) {
    if (static_cast<unsigned char>(*p) == 0x1b) {
      p = skip_ansi_escape_sequence(p);
      continue;
    }
    if (!skip_utf8_continuation_bytes || (*p & 0xC0) != 0x80)
      ++length;
    ++p;
  }
  return length;
}

inline size_t get_sequence_length(const std::string &text, const std::string &locale,
                                  bool is_multi_byte_character_support_enabled) {
  if (!is_multi_byte_character_support_enabled)
    return count_bytes_outside_ansi_escapes(text, false);

#if defined(_WIN32) || defined(_WIN64)
  (void)locale; // unused parameter
  return static_cast<size_t>(get_display_width(text, text.size()));
#elif defined(__unix__) || defined(__unix) || defined(__APPLE__)
  auto result = get_wcswidth(text, locale, text.size());
  if (result >= 0)
    return result;
  else
    return count_bytes_outside_ansi_escapes(text, true);
#endif
}

// Returns the number of bytes from the start of `text` whose rendered width
// does not exceed max_width, without ever splitting a multi-byte character
// (or ANSI escape sequence) in half. Always advances past at least one
// character when text is non-empty, even if that character alone is wider
// than max_width, so callers that force-split long words always make
// progress. Mirrors get_sequence_length()'s width accounting exactly, so a
// prefix of this many bytes is guaranteed to measure as <= max_width.
inline size_t byte_offset_for_width(const std::string &text, const std::string &locale,
                                    bool is_multi_byte_character_support_enabled,
                                    size_t max_width) {
  if (!is_multi_byte_character_support_enabled)
    return (std::min)(max_width, text.size());

#if defined(_WIN32) || defined(_WIN64)
  (void)locale;
  size_t consumed_width = 0;
  bool first_character = true;
  const char *p = text.c_str();
  while (*p != '\0') {
    if (static_cast<unsigned char>(*p) == 0x1b) {
      p = skip_ansi_escape_sequence(p);
      continue;
    }
    const char *character_start = p;
    size_t length;
    const char32_t codepoint = decode_utf8_codepoint(p, length);
    int character_width = mk_wcwidth(codepoint);
    if (character_width < 0)
      character_width = 0;
    if (!first_character && consumed_width + static_cast<size_t>(character_width) > max_width)
      return static_cast<size_t>(character_start - text.c_str());
    consumed_width += static_cast<size_t>(character_width);
    first_character = false;
    p = character_start + length;
  }
  return text.size();
#elif defined(__unix__) || defined(__unix) || defined(__APPLE__)
  const char *previous_locale = std::setlocale(LC_CTYPE, nullptr);
  const std::string saved_locale = previous_locale != nullptr ? previous_locale : "";
  std::setlocale(LC_CTYPE, locale.c_str());

  const char *p = text.c_str();
  std::mbstate_t state = std::mbstate_t();
  size_t consumed_width = 0;
  bool first_character = true;
  size_t result = text.size();

  while (*p != '\0') {
    if (static_cast<unsigned char>(*p) == 0x1b) {
      p = skip_ansi_escape_sequence(p);
      continue;
    }

    const char *character_start = p;
    wchar_t wide_character;
    size_t length = std::mbrtowc(&wide_character, p, MB_CUR_MAX, &state);

    if (length == static_cast<size_t>(-2))
      break; // truncated multi-byte character at the end of the string

    if (length == static_cast<size_t>(-1)) {
      state = std::mbstate_t();
      length = 1; // invalid byte: treat as width 1 and resynchronize
    } else if (length == 0) {
      length = 1; // embedded null: treat as a 1-byte character
    }

    int character_width = wcwidth(wide_character);
    if (character_width < 0)
      character_width = 0;

    if (!first_character && consumed_width + static_cast<size_t>(character_width) > max_width) {
      result = static_cast<size_t>(character_start - text.c_str());
      break;
    }

    consumed_width += static_cast<size_t>(character_width);
    first_character = false;
    p = character_start + length;
  }

  if (!saved_locale.empty())
    std::setlocale(LC_CTYPE, saved_locale.c_str());
  return result;
#endif
}

} // namespace tabulate
